# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bcca7f4312c432fa305074dd40e1b7cdce2453b1bd8f7e857de7a93b30ac526b9e453498618a47effb952dcc098a2b3e8c153a3dd0fae939dbd01b4d6be6583

test:
  secret_key_base: 1594f65a8d10606dd740f2c9ee0e5ccf43decdf30f8d666d41dfc354102e946919e51cb845b313e7a90787f1da5a7d89deb6b353ffe11c12bdd13aa539e19524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
